CREATE TABLE IF NOT EXISTS orders (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    sku VARCHAR(100) NOT NULL,
    qty INT NOT NULL,
    price DOUBLE NOT NULL,
    order_date DATE NOT NULL,
    shipped BOOLEAN NOT NULL
);